apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  template:
    metadata:
      name: ui
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: mesosphere/dcosappstudio:dcosappstudio-smartcity-ui-v1.11.rc4-1.4.0-0.0.1
        imagePullPolicy: Always
        env:
        - name: APPDEF
          value: "{'name':'Smart City Platform','showLocation':'true','fields':[{'name':'id','pivot':'false','type':'Long'},{'name':'location','pivot':'false','type':'Location'},{'name':'event_timestamp','pivot':'false','type':'Date/time'},{'name':'message1','pivot':'false','type':'String'},{'name':'type','pivot':'false','type':'Integer'},{'name':'status','pivot':'false','type':'String'},{'name':'value','pivot':'true','type':'Double'},{'name':'status','pivot':'false','type':'String'},{'name':'message2','pivot':'false','type':'String'},{'name':'intvalue2','pivot':'false','type':'Integer'},{'name':'intvalue1','pivot':'false','type':'Integer'}],'transformer':'%09%0A%09%09%0A%09%2F%2F%20Raw%20message%20available%20as%3A%20rawtext%3B%0A%09%2F%2F%20save%20result%20in%20variable%3A%20result%0A%09%2F%2F%20result%20is%20of%20type%20String%0A%09%0A%09%2F%2F%20get%20json%20object%3A%20JSON.parse(rawtext)%3B%0A%09%2F%2F%20also%20available%20fields%5B%5D%20and%20types%5B%5D%3A%0A%09%2F%2F%20e.g.%20fields%5B0%5D%3D%3D%20%22id%22%2C%20%20types%5B0%5D%3D%3D%22Long%22%0A%0A%09%2F%2F%20Transform%20incoming%20xml%20to%20json%3A%20%20json%3D%20parseXML(rawtext)%3B%20result%3D%20JSON.stringify(json)%3B%0A%09%2F%2F%20uses%20npm%20xml2js%0A%09%2F%2F%20Transform%20incoming%20yaml%20to%20json%3A%20let%20json%3DyamlParser.parse(rawtext)%3B%20console.log(%22JSON%3A%20%22%2BJSON.stringify(json))%3B%20result%3D%20JSON.stringify(json)%3B%20%0A%09%2F%2F%20uses%20npm%20yamljs%0A%09%2F%2F%20Rename%20field%3A%20let%20json%3D%20JSON.parse(rawtext)%3B%20json.newname%3D%20json.oldname%3B%20delete%20json.oldname%3B%0A%0A%09console.log(%22In%20%3A%20%22%2Brawtext)%3B%0A%2F*%0A%09let%20json%3D%20JSON.parse(rawtext)%3B%0A%20%20%20%20%20%20%20%20for%20(var%20key%20in%20json)%20%7B%0A%20%20%09%09%09if%20(json.hasOwnProperty(key))%20%7B%0A%09%09%09%09%20%20if(typesByName%5Bkey%5D%3D%3D%3D%20%22String%22)%0A%09%09%09%09%20%20%09json%5Bkey%5D%3D%20%22Great!%22%3B%0A%09%09%09%7D%0A%09%09%7D%0A%0A%09result%3D%20JSON.stringify(json)%3B%0A*%2F%0A%09result%3D%20rawtext%3B%0A%09console.log(%22After%20transformation%3A%20%22%2Bresult)%3B%0A%09%09%09%09%09%0A%09%09%09%09%09','topic':'citydata','table':'citydata','keyspace':'london','path':'smartcity','creator':'http://localhost:3000','dockerrepo':'mesosphere/dcosappstudio','img':'','vis':'','dash':'','hideloader':'true'}"
        - name: LISTENER
          value: http://messagelistener/data
        - name: KAFKA_SERVICE
          value: master.mesos:2181/dcos-service-prod__dataservices__kafka
        - name: CASSANDRA_SERVICE
          value: node.proddataservicescassandra.l4lb.thisdcos.directory:9042
        - name: PUBLICNODE
          value: $PUBLICNODEIP
        - name: UISERVICE
          value: http://uiservice
        - name: CLUSTER_URL
          value: CLUSTER_URL_TOKEN
        - name: APPDIR
          value: /opt/app
        - name: DASHBOARDURL
          value: 
        ports:
        - containerPort: 3000
        - containerPort: 10500
---
kind: Service
apiVersion: v1
metadata:
  name: ui
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3020
      nodePort: 31110
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: uisocketio
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10500
      nodePort: 31500
  type: NodePort